"""
The disclaimer is appended by CODE, not generated by the LLM - this guarantees
it's always present, worded identically every time, and never accidentally
dropped or paraphrased. Applied to EVERY response, per the explicit instruction
to always answer + disclaimer rather than selectively refusing or gating.
"""

DISCLAIMER = {
    "en": "⚠️ This isn't a substitute for professional medical advice — consult a pharmacist or doctor before use.",
    "ar": "⚠️ هذا لا يغني عن الاستشارة الطبية المتخصصة — يرجى استشارة الصيدلي أو الطبيب قبل الاستخدام.",
}


def append_disclaimer(answer_text: str, lang: str) -> str:
    disclaimer = DISCLAIMER.get(lang, DISCLAIMER["en"])
    return f"{answer_text}\n\n{disclaimer}"